apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260621-004629-lqkas8c2ch8t-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260621-004629-lqkas8c2ch8t.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260621-004629-lqkas8c2ch8t-service
            port:
              number: 80
